// Generated by `tools/gen_dlmm_events.py`. Do not hand-edit.

pub mod add_liquidity;
pub mod claim_fee;
pub mod claim_fee2;
pub mod claim_reward;
pub mod claim_reward2;
pub mod composition_fee;
pub mod decrease_position_length;
pub mod dynamic_fee_parameter_update;
pub mod fee_parameter_update;
pub mod fund_reward;
pub mod go_to_a_bin;
pub mod increase_observation;
pub mod increase_position_length;
pub mod initialize_reward;
pub mod lb_pair_create;
pub mod position_close;
pub mod position_create;
pub mod rebalancing;
pub mod remove_liquidity;
pub mod swap;
pub mod update_position_lock_release_point;
pub mod update_position_operator;
pub mod update_reward_duration;
pub mod update_reward_funder;
pub mod withdraw_ineligible_reward;

pub use add_liquidity::{ AddLiquidityEvent, ADD_LIQUIDITY_EVENT_DISCRIMINATOR };
pub use claim_fee::{ ClaimFeeEvent, CLAIM_FEE_EVENT_DISCRIMINATOR };
pub use claim_fee2::{ ClaimFee2Event, CLAIM_FEE2_EVENT_DISCRIMINATOR };
pub use claim_reward::{ ClaimRewardEvent, CLAIM_REWARD_EVENT_DISCRIMINATOR };
pub use claim_reward2::{ ClaimReward2Event, CLAIM_REWARD2_EVENT_DISCRIMINATOR };
pub use composition_fee::{ CompositionFeeEvent, COMPOSITION_FEE_EVENT_DISCRIMINATOR };
pub use decrease_position_length::{ DecreasePositionLengthEvent, DECREASE_POSITION_LENGTH_EVENT_DISCRIMINATOR };
pub use dynamic_fee_parameter_update::{ DynamicFeeParameterUpdateEvent, DYNAMIC_FEE_PARAMETER_UPDATE_EVENT_DISCRIMINATOR };
pub use fee_parameter_update::{ FeeParameterUpdateEvent, FEE_PARAMETER_UPDATE_EVENT_DISCRIMINATOR };
pub use fund_reward::{ FundRewardEvent, FUND_REWARD_EVENT_DISCRIMINATOR };
pub use go_to_a_bin::{ GoToABinEvent, GO_TO_A_BIN_EVENT_DISCRIMINATOR };
pub use increase_observation::{ IncreaseObservationEvent, INCREASE_OBSERVATION_EVENT_DISCRIMINATOR };
pub use increase_position_length::{ IncreasePositionLengthEvent, INCREASE_POSITION_LENGTH_EVENT_DISCRIMINATOR };
pub use initialize_reward::{ InitializeRewardEvent, INITIALIZE_REWARD_EVENT_DISCRIMINATOR };
pub use lb_pair_create::{ LbPairCreateEvent, LB_PAIR_CREATE_EVENT_DISCRIMINATOR };
pub use position_close::{ PositionCloseEvent, POSITION_CLOSE_EVENT_DISCRIMINATOR };
pub use position_create::{ PositionCreateEvent, POSITION_CREATE_EVENT_DISCRIMINATOR };
pub use rebalancing::{ RebalancingEvent, REBALANCING_EVENT_DISCRIMINATOR };
pub use remove_liquidity::{ RemoveLiquidityEvent, REMOVE_LIQUIDITY_EVENT_DISCRIMINATOR };
pub use swap::{ SwapEvent, SWAP_EVENT_DISCRIMINATOR };
pub use update_position_lock_release_point::{ UpdatePositionLockReleasePointEvent, UPDATE_POSITION_LOCK_RELEASE_POINT_EVENT_DISCRIMINATOR };
pub use update_position_operator::{ UpdatePositionOperatorEvent, UPDATE_POSITION_OPERATOR_EVENT_DISCRIMINATOR };
pub use update_reward_duration::{ UpdateRewardDurationEvent, UPDATE_REWARD_DURATION_EVENT_DISCRIMINATOR };
pub use update_reward_funder::{ UpdateRewardFunderEvent, UPDATE_REWARD_FUNDER_EVENT_DISCRIMINATOR };
pub use withdraw_ineligible_reward::{ WithdrawIneligibleRewardEvent, WITHDRAW_INELIGIBLE_REWARD_EVENT_DISCRIMINATOR };

/// One variant per DLMM on-chain event. Variants wrap the SDK's
/// borsh-derived type structs verbatim.
#[derive(Debug, Clone)]
pub enum MeteoraDlmmEvent {
    AddLiquidity(add_liquidity::AddLiquidityEvent),
    ClaimFee(claim_fee::ClaimFeeEvent),
    ClaimFee2(claim_fee2::ClaimFee2Event),
    ClaimReward(claim_reward::ClaimRewardEvent),
    ClaimReward2(claim_reward2::ClaimReward2Event),
    CompositionFee(composition_fee::CompositionFeeEvent),
    DecreasePositionLength(decrease_position_length::DecreasePositionLengthEvent),
    DynamicFeeParameterUpdate(dynamic_fee_parameter_update::DynamicFeeParameterUpdateEvent),
    FeeParameterUpdate(fee_parameter_update::FeeParameterUpdateEvent),
    FundReward(fund_reward::FundRewardEvent),
    GoToABin(go_to_a_bin::GoToABinEvent),
    IncreaseObservation(increase_observation::IncreaseObservationEvent),
    IncreasePositionLength(increase_position_length::IncreasePositionLengthEvent),
    InitializeReward(initialize_reward::InitializeRewardEvent),
    LbPairCreate(lb_pair_create::LbPairCreateEvent),
    PositionClose(position_close::PositionCloseEvent),
    PositionCreate(position_create::PositionCreateEvent),
    Rebalancing(rebalancing::RebalancingEvent),
    RemoveLiquidity(remove_liquidity::RemoveLiquidityEvent),
    Swap(swap::SwapEvent),
    UpdatePositionLockReleasePoint(update_position_lock_release_point::UpdatePositionLockReleasePointEvent),
    UpdatePositionOperator(update_position_operator::UpdatePositionOperatorEvent),
    UpdateRewardDuration(update_reward_duration::UpdateRewardDurationEvent),
    UpdateRewardFunder(update_reward_funder::UpdateRewardFunderEvent),
    WithdrawIneligibleReward(withdraw_ineligible_reward::WithdrawIneligibleRewardEvent),
}

/// Internal dispatch: given a stripped 8-byte per-event
/// discriminator + body, return the typed event. Public surface is
/// [`super::parse_event_body`] which also strips the anchor envelope.
fn dispatch(disc: &[u8; 8], body: &[u8]) -> Result<MeteoraDlmmEvent, crate::parsing::InstructionParseError> {
    match *disc {
        add_liquidity::ADD_LIQUIDITY_EVENT_DISCRIMINATOR => add_liquidity::decode(body).map(MeteoraDlmmEvent::AddLiquidity),
        claim_fee::CLAIM_FEE_EVENT_DISCRIMINATOR => claim_fee::decode(body).map(MeteoraDlmmEvent::ClaimFee),
        claim_fee2::CLAIM_FEE2_EVENT_DISCRIMINATOR => claim_fee2::decode(body).map(MeteoraDlmmEvent::ClaimFee2),
        claim_reward::CLAIM_REWARD_EVENT_DISCRIMINATOR => claim_reward::decode(body).map(MeteoraDlmmEvent::ClaimReward),
        claim_reward2::CLAIM_REWARD2_EVENT_DISCRIMINATOR => claim_reward2::decode(body).map(MeteoraDlmmEvent::ClaimReward2),
        composition_fee::COMPOSITION_FEE_EVENT_DISCRIMINATOR => composition_fee::decode(body).map(MeteoraDlmmEvent::CompositionFee),
        decrease_position_length::DECREASE_POSITION_LENGTH_EVENT_DISCRIMINATOR => decrease_position_length::decode(body).map(MeteoraDlmmEvent::DecreasePositionLength),
        dynamic_fee_parameter_update::DYNAMIC_FEE_PARAMETER_UPDATE_EVENT_DISCRIMINATOR => dynamic_fee_parameter_update::decode(body).map(MeteoraDlmmEvent::DynamicFeeParameterUpdate),
        fee_parameter_update::FEE_PARAMETER_UPDATE_EVENT_DISCRIMINATOR => fee_parameter_update::decode(body).map(MeteoraDlmmEvent::FeeParameterUpdate),
        fund_reward::FUND_REWARD_EVENT_DISCRIMINATOR => fund_reward::decode(body).map(MeteoraDlmmEvent::FundReward),
        go_to_a_bin::GO_TO_A_BIN_EVENT_DISCRIMINATOR => go_to_a_bin::decode(body).map(MeteoraDlmmEvent::GoToABin),
        increase_observation::INCREASE_OBSERVATION_EVENT_DISCRIMINATOR => increase_observation::decode(body).map(MeteoraDlmmEvent::IncreaseObservation),
        increase_position_length::INCREASE_POSITION_LENGTH_EVENT_DISCRIMINATOR => increase_position_length::decode(body).map(MeteoraDlmmEvent::IncreasePositionLength),
        initialize_reward::INITIALIZE_REWARD_EVENT_DISCRIMINATOR => initialize_reward::decode(body).map(MeteoraDlmmEvent::InitializeReward),
        lb_pair_create::LB_PAIR_CREATE_EVENT_DISCRIMINATOR => lb_pair_create::decode(body).map(MeteoraDlmmEvent::LbPairCreate),
        position_close::POSITION_CLOSE_EVENT_DISCRIMINATOR => position_close::decode(body).map(MeteoraDlmmEvent::PositionClose),
        position_create::POSITION_CREATE_EVENT_DISCRIMINATOR => position_create::decode(body).map(MeteoraDlmmEvent::PositionCreate),
        rebalancing::REBALANCING_EVENT_DISCRIMINATOR => rebalancing::decode(body).map(MeteoraDlmmEvent::Rebalancing),
        remove_liquidity::REMOVE_LIQUIDITY_EVENT_DISCRIMINATOR => remove_liquidity::decode(body).map(MeteoraDlmmEvent::RemoveLiquidity),
        swap::SWAP_EVENT_DISCRIMINATOR => swap::decode(body).map(MeteoraDlmmEvent::Swap),
        update_position_lock_release_point::UPDATE_POSITION_LOCK_RELEASE_POINT_EVENT_DISCRIMINATOR => update_position_lock_release_point::decode(body).map(MeteoraDlmmEvent::UpdatePositionLockReleasePoint),
        update_position_operator::UPDATE_POSITION_OPERATOR_EVENT_DISCRIMINATOR => update_position_operator::decode(body).map(MeteoraDlmmEvent::UpdatePositionOperator),
        update_reward_duration::UPDATE_REWARD_DURATION_EVENT_DISCRIMINATOR => update_reward_duration::decode(body).map(MeteoraDlmmEvent::UpdateRewardDuration),
        update_reward_funder::UPDATE_REWARD_FUNDER_EVENT_DISCRIMINATOR => update_reward_funder::decode(body).map(MeteoraDlmmEvent::UpdateRewardFunder),
        withdraw_ineligible_reward::WITHDRAW_INELIGIBLE_REWARD_EVENT_DISCRIMINATOR => withdraw_ineligible_reward::decode(body).map(MeteoraDlmmEvent::WithdrawIneligibleReward),
        other => Err(crate::parsing::InstructionParseError::UnknownDiscriminator(other)),
    }
}
