//! Raydium V4 swap instructions and builders.
//!
//! Uses 1-byte instruction indices (not 8-byte Anchor discriminators).

use solana_program::pubkey::Pubkey;
use solana_protocols_macros::{AccountMetas, InstructionData};
use solana_sdk::instruction::Instruction;
use spl_associated_token_account::get_associated_token_address;

use super::super::accounts::RaydiumV4Keys;
use super::super::constants::{PROGRAM_ID, SWAP_BASE_IN_IX, SWAP_BASE_OUT_IX};
use crate::error::Result;
use crate::traits::InstructionBuilder;

// =============================================================================
// SwapBaseIn - Swap with exact input amount
// =============================================================================

/// SwapBaseIn instruction parameters.
///
/// Uses 1-byte instruction index (0x09).
#[derive(Debug, Clone, borsh::BorshDeserialize, borsh::BorshSerialize, InstructionData)]
#[instruction_data(discriminator = [SWAP_BASE_IN_IX], discriminator_size = 1, unverified = "this protocol is not modelled to the pumpfun/pumpswap standard yet; pinning params here would claim a verification the rest of the vertical does not have")]
pub struct SwapBaseInParams {
    /// Amount of tokens to swap in.
    pub amount_in: u64,
    /// Minimum amount of tokens to receive (slippage protection).
    pub minimum_amount_out: u64,
}

impl SwapBaseInParams {
    /// Create new swap parameters.
    #[must_use]
    pub fn new(amount_in: u64, minimum_amount_out: u64) -> Self {
        Self {
            amount_in,
            minimum_amount_out,
        }
    }

    /// Create parameters from swap output with slippage.
    ///
    /// For a buy: amount_in = SOL, minimum_amount_out = tokens (with slippage).
    /// For a sell: amount_in = tokens, minimum_amount_out = SOL (with slippage).
    #[must_use]
    pub fn from_swap_output(amount_in: u64, expected_out: u64, slippage_bps: u16) -> Self {
        let min_out = (expected_out as u128 * (10000 - slippage_bps as u128) / 10000) as u64;
        Self {
            amount_in,
            minimum_amount_out: min_out,
        }
    }
}

// FromInstructionData for SwapBaseInParams — auto-generated by #[derive(borsh::BorshDeserialize, borsh::BorshSerialize, InstructionData)] macro
// Expects data AFTER the discriminator byte (per trait contract).

/// SwapBaseIn instruction accounts.
///
/// Account order matches the on-chain program expectation.
#[derive(Debug, Clone, AccountMetas)]
#[accounts(
    unverified = "this protocol is not modelled to the pumpfun/pumpswap standard yet; a golden fixture here would claim a verification the rest of the vertical does not have"
)]
pub struct SwapBaseInAccounts {
    /// Token program.
    #[account]
    pub token_program: Pubkey,

    /// AMM ID (pool account).
    #[account(writable)]
    pub amm_id: Pubkey,

    /// AMM authority (PDA).
    #[account]
    pub amm_authority: Pubkey,

    /// AMM open orders (Serum).
    #[account(writable)]
    pub amm_open_orders: Pubkey,

    /// AMM target orders (can be default pubkey for non-orderbook pools).
    #[account(writable)]
    pub amm_target_orders: Pubkey,

    /// Pool coin vault (base token).
    #[account(writable)]
    pub pool_coin_token_account: Pubkey,

    /// Pool PC vault (quote token).
    #[account(writable)]
    pub pool_pc_token_account: Pubkey,

    /// Serum program ID.
    #[account]
    pub serum_program_id: Pubkey,

    /// Serum market.
    #[account(writable)]
    pub serum_market: Pubkey,

    /// Serum bids.
    #[account(writable)]
    pub serum_bids: Pubkey,

    /// Serum asks.
    #[account(writable)]
    pub serum_asks: Pubkey,

    /// Serum event queue.
    #[account(writable)]
    pub serum_event_queue: Pubkey,

    /// Serum coin vault.
    #[account(writable)]
    pub serum_coin_vault_account: Pubkey,

    /// Serum PC vault.
    #[account(writable)]
    pub serum_pc_vault_account: Pubkey,

    /// Serum vault signer.
    #[account]
    pub serum_vault_signer: Pubkey,

    /// User source token account.
    #[account(writable)]
    pub user_source_token_account: Pubkey,

    /// User destination token account.
    #[account(writable)]
    pub user_destination_token_account: Pubkey,

    /// User wallet (signer).
    #[account(signer)]
    pub user_source_owner: Pubkey,
}

impl SwapBaseInAccounts {
    /// Create swap accounts from pool keys and user.
    ///
    /// For a buy (SOL→token): source = quote ATA, dest = base ATA.
    /// For a sell (token→SOL): source = base ATA, dest = quote ATA.
    #[must_use]
    pub fn from_keys(
        keys: &RaydiumV4Keys,
        user: &Pubkey,
        source_mint: &Pubkey,
        dest_mint: &Pubkey,
    ) -> Self {
        SwapBaseInAccounts {
            token_program: spl_token::id(),
            amm_id: keys.amm_id,
            amm_authority: keys.amm_authority,
            amm_open_orders: keys.amm_open_orders,
            amm_target_orders: keys.amm_target_orders,
            pool_coin_token_account: keys.base_vault,
            pool_pc_token_account: keys.quote_vault,
            serum_program_id: keys.serum_program_id,
            serum_market: keys.serum_market,
            serum_bids: keys.serum_bids,
            serum_asks: keys.serum_asks,
            serum_event_queue: keys.serum_event_queue,
            serum_coin_vault_account: keys.serum_coin_vault,
            serum_pc_vault_account: keys.serum_pc_vault,
            serum_vault_signer: keys.serum_vault_signer,
            user_source_token_account: get_associated_token_address(user, source_mint),
            user_destination_token_account: get_associated_token_address(user, dest_mint),
            user_source_owner: *user,
        }
    }

    /// Create buy accounts (SOL → base token).
    #[must_use]
    pub fn for_buy(keys: &RaydiumV4Keys, user: &Pubkey) -> Self {
        Self::from_keys(keys, user, &keys.quote_mint, &keys.base_mint)
    }

    /// Create sell accounts (base token → SOL).
    #[must_use]
    pub fn for_sell(keys: &RaydiumV4Keys, user: &Pubkey) -> Self {
        Self::from_keys(keys, user, &keys.base_mint, &keys.quote_mint)
    }
}

// FromAccountKeys for SwapBaseInAccounts — auto-generated by #[derive(AccountMetas)] macro

// =============================================================================
// SwapBaseOut - Swap with exact output amount
// =============================================================================

/// SwapBaseOut instruction parameters.
///
/// Uses 1-byte instruction index (0x0B).
#[derive(Debug, Clone, borsh::BorshDeserialize, borsh::BorshSerialize, InstructionData)]
#[instruction_data(discriminator = [SWAP_BASE_OUT_IX], discriminator_size = 1, unverified = "this protocol is not modelled to the pumpfun/pumpswap standard yet; pinning params here would claim a verification the rest of the vertical does not have")]
pub struct SwapBaseOutParams {
    /// Maximum amount of tokens to swap in.
    pub max_amount_in: u64,
    /// Exact amount of tokens to receive.
    pub amount_out: u64,
}

impl SwapBaseOutParams {
    /// Create new swap parameters.
    #[must_use]
    pub fn new(max_amount_in: u64, amount_out: u64) -> Self {
        Self {
            max_amount_in,
            amount_out,
        }
    }

    /// Create parameters from swap output with slippage.
    #[must_use]
    pub fn from_swap_output(expected_in: u64, amount_out: u64, slippage_bps: u16) -> Self {
        let max_in = (expected_in as u128 * (10000 + slippage_bps as u128) / 10000) as u64;
        Self {
            max_amount_in: max_in,
            amount_out,
        }
    }
}

// FromInstructionData for SwapBaseOutParams — auto-generated by #[derive(borsh::BorshDeserialize, borsh::BorshSerialize, InstructionData)] macro

/// SwapBaseOut instruction accounts.
///
/// Same layout as SwapBaseIn.
/// Account list for Raydium V4 `swap_base_out`.
///
/// A copy of `swap_base_in`'s layout rather than an alias: every
/// discriminator owns its own accounts struct, so each one's fixtures and
/// IDL entry pin only itself.
#[derive(Debug, Clone, AccountMetas)]
#[accounts(
    unverified = "this protocol is not modelled to the pumpfun/pumpswap standard yet; a golden fixture here would claim a verification the rest of the vertical does not have"
)]
pub struct SwapBaseOutAccounts {
    /// Token program.
    #[account]
    pub token_program: Pubkey,

    /// AMM ID (pool account).
    #[account(writable)]
    pub amm_id: Pubkey,

    /// AMM authority (PDA).
    #[account]
    pub amm_authority: Pubkey,

    /// AMM open orders (Serum).
    #[account(writable)]
    pub amm_open_orders: Pubkey,

    /// AMM target orders (can be default pubkey for non-orderbook pools).
    #[account(writable)]
    pub amm_target_orders: Pubkey,

    /// Pool coin vault (base token).
    #[account(writable)]
    pub pool_coin_token_account: Pubkey,

    /// Pool PC vault (quote token).
    #[account(writable)]
    pub pool_pc_token_account: Pubkey,

    /// Serum program ID.
    #[account]
    pub serum_program_id: Pubkey,

    /// Serum market.
    #[account(writable)]
    pub serum_market: Pubkey,

    /// Serum bids.
    #[account(writable)]
    pub serum_bids: Pubkey,

    /// Serum asks.
    #[account(writable)]
    pub serum_asks: Pubkey,

    /// Serum event queue.
    #[account(writable)]
    pub serum_event_queue: Pubkey,

    /// Serum coin vault.
    #[account(writable)]
    pub serum_coin_vault_account: Pubkey,

    /// Serum PC vault.
    #[account(writable)]
    pub serum_pc_vault_account: Pubkey,

    /// Serum vault signer.
    #[account]
    pub serum_vault_signer: Pubkey,

    /// User source token account.
    #[account(writable)]
    pub user_source_token_account: Pubkey,

    /// User destination token account.
    #[account(writable)]
    pub user_destination_token_account: Pubkey,

    /// User wallet (signer).
    #[account(signer)]
    pub user_source_owner: Pubkey,
}

// =============================================================================
// Builders
// =============================================================================

/// Builder for Raydium V4 SwapBaseIn instructions (exact input).
pub struct SwapBaseInBuilder;

impl InstructionBuilder for SwapBaseInBuilder {
    type Keys = (RaydiumV4Keys, bool); // (keys, is_buy)
    type Params = SwapBaseInParams;

    fn build_swap_instruction(
        keys: &Self::Keys,
        user: &Pubkey,
        params: Self::Params,
    ) -> Result<Instruction> {
        let (pool_keys, is_buy) = keys;
        let accounts = if *is_buy {
            SwapBaseInAccounts::for_buy(pool_keys, user)
        } else {
            SwapBaseInAccounts::for_sell(pool_keys, user)
        };

        Ok(Instruction {
            program_id: PROGRAM_ID,
            accounts: accounts.to_account_metas(),
            data: params.to_data(),
        })
    }

    fn build_swap_with_setup(
        keys: &Self::Keys,
        user: &Pubkey,
        params: Self::Params,
        create_ata: bool,
    ) -> Result<Vec<Instruction>> {
        let mut instructions = Vec::with_capacity(2);
        let (pool_keys, is_buy) = keys;

        if create_ata {
            // Create the destination token ATA
            let dest_mint = if *is_buy {
                &pool_keys.base_mint
            } else {
                &pool_keys.quote_mint
            };
            let ata_ix = spl_associated_token_account::instruction::create_associated_token_account_idempotent(
                user,
                user,
                dest_mint,
                &spl_token::id(),
            );
            instructions.push(ata_ix);
        }

        instructions.push(Self::build_swap_instruction(keys, user, params)?);

        Ok(instructions)
    }
}

impl SwapBaseInBuilder {
    /// Build a buy instruction (SOL → token, exact input).
    #[must_use]
    pub fn buy(
        keys: &RaydiumV4Keys,
        user: &Pubkey,
        amount_in: u64,
        minimum_amount_out: u64,
    ) -> Instruction {
        Self::build_swap_instruction(
            &(keys.clone(), true),
            user,
            SwapBaseInParams::new(amount_in, minimum_amount_out),
        )
        .expect("SwapBaseInBuilder::build should not fail")
    }

    /// Build a sell instruction (token → SOL, exact input).
    #[must_use]
    pub fn sell(
        keys: &RaydiumV4Keys,
        user: &Pubkey,
        amount_in: u64,
        minimum_amount_out: u64,
    ) -> Instruction {
        Self::build_swap_instruction(
            &(keys.clone(), false),
            user,
            SwapBaseInParams::new(amount_in, minimum_amount_out),
        )
        .expect("SwapBaseInBuilder::build should not fail")
    }

    /// Build a buy instruction with ATA creation.
    #[must_use]
    pub fn buy_with_ata(
        keys: &RaydiumV4Keys,
        user: &Pubkey,
        amount_in: u64,
        minimum_amount_out: u64,
    ) -> Vec<Instruction> {
        Self::build_swap_with_setup(
            &(keys.clone(), true),
            user,
            SwapBaseInParams::new(amount_in, minimum_amount_out),
            true,
        )
        .expect("SwapBaseInBuilder::build_with_setup should not fail")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parsing::FromInstructionData;

    fn make_test_keys() -> RaydiumV4Keys {
        RaydiumV4Keys {
            amm_id: Pubkey::new_unique(),
            amm_authority: Pubkey::new_unique(),
            amm_open_orders: Pubkey::new_unique(),
            amm_target_orders: Pubkey::new_unique(),
            base_vault: Pubkey::new_unique(),
            quote_vault: Pubkey::new_unique(),
            base_mint: Pubkey::new_unique(),
            quote_mint: Pubkey::new_unique(),
            serum_market: Pubkey::new_unique(),
            serum_program_id: Pubkey::new_unique(),
            serum_bids: Pubkey::new_unique(),
            serum_asks: Pubkey::new_unique(),
            serum_event_queue: Pubkey::new_unique(),
            serum_coin_vault: Pubkey::new_unique(),
            serum_pc_vault: Pubkey::new_unique(),
            serum_vault_signer: Pubkey::new_unique(),
        }
    }

    #[test]
    fn swap_base_in_params_to_data() {
        let params = SwapBaseInParams::new(1_000_000_000, 900_000_000);
        let data = params.to_data();

        assert_eq!(data.len(), 17); // 1 + 8 + 8
        assert_eq!(data[0], SWAP_BASE_IN_IX);

        let amount_in = u64::from_le_bytes(data[1..9].try_into().unwrap());
        let min_out = u64::from_le_bytes(data[9..17].try_into().unwrap());
        assert_eq!(amount_in, 1_000_000_000);
        assert_eq!(min_out, 900_000_000);
    }

    #[test]
    fn swap_base_in_params_from_data() {
        let original = SwapBaseInParams::new(1_000_000_000, 900_000_000);
        let data = original.to_data();

        // Skip 1-byte discriminator — from_instruction_data expects data after disc
        let parsed = SwapBaseInParams::from_instruction_data(&data[1..]).unwrap();
        assert_eq!(parsed.amount_in, 1_000_000_000);
        assert_eq!(parsed.minimum_amount_out, 900_000_000);
    }

    #[test]
    fn swap_base_in_from_swap_output() {
        let params = SwapBaseInParams::from_swap_output(1_000_000_000, 100_000_000, 100);
        assert_eq!(params.amount_in, 1_000_000_000);
        assert_eq!(params.minimum_amount_out, 99_000_000); // 1% slippage
    }

    #[test]
    fn swap_base_out_params_to_data() {
        let params = SwapBaseOutParams::new(1_100_000_000, 1_000_000_000);
        let data = params.to_data();

        assert_eq!(data.len(), 17); // 1 + 8 + 8
        assert_eq!(data[0], SWAP_BASE_OUT_IX);
    }

    #[test]
    fn swap_base_out_from_swap_output() {
        let params = SwapBaseOutParams::from_swap_output(100_000_000, 1_000_000_000, 100);
        assert_eq!(params.max_amount_in, 101_000_000); // 1% slippage
        assert_eq!(params.amount_out, 1_000_000_000);
    }

    #[test]
    fn buy_accounts_from_keys() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let accounts = SwapBaseInAccounts::for_buy(&keys, &user);

        assert_eq!(accounts.amm_id, keys.amm_id);
        assert_eq!(accounts.amm_authority, keys.amm_authority);
        assert_eq!(accounts.pool_coin_token_account, keys.base_vault);
        assert_eq!(accounts.pool_pc_token_account, keys.quote_vault);
        assert_eq!(accounts.user_source_owner, user);
        // Buy: source = quote ATA, dest = base ATA
        assert_eq!(
            accounts.user_source_token_account,
            get_associated_token_address(&user, &keys.quote_mint)
        );
        assert_eq!(
            accounts.user_destination_token_account,
            get_associated_token_address(&user, &keys.base_mint)
        );
    }

    #[test]
    fn sell_accounts_from_keys() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let accounts = SwapBaseInAccounts::for_sell(&keys, &user);

        // Sell: source = base ATA, dest = quote ATA
        assert_eq!(
            accounts.user_source_token_account,
            get_associated_token_address(&user, &keys.base_mint)
        );
        assert_eq!(
            accounts.user_destination_token_account,
            get_associated_token_address(&user, &keys.quote_mint)
        );
    }

    #[test]
    fn builder_buy_creates_instruction() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let ix = SwapBaseInBuilder::buy(&keys, &user, 1_000_000_000, 900_000);

        assert_eq!(ix.program_id, PROGRAM_ID);
        assert_eq!(ix.accounts.len(), 18);
        assert_eq!(ix.data[0], SWAP_BASE_IN_IX);

        let user_account = ix.accounts.iter().find(|a| a.pubkey == user);
        assert!(user_account.is_some());
        assert!(user_account.unwrap().is_signer);
    }

    #[test]
    fn builder_sell_creates_instruction() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let ix = SwapBaseInBuilder::sell(&keys, &user, 1_000_000, 900_000_000);

        assert_eq!(ix.program_id, PROGRAM_ID);
        assert_eq!(ix.data[0], SWAP_BASE_IN_IX);
    }

    #[test]
    fn builder_buy_with_ata() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let instructions = SwapBaseInBuilder::buy_with_ata(&keys, &user, 1_000_000_000, 900_000);

        assert_eq!(instructions.len(), 2);
        assert_eq!(
            instructions[0].program_id,
            spl_associated_token_account::id()
        );
        assert_eq!(instructions[1].program_id, PROGRAM_ID);
    }
}
