//! `solana-account-traits` handler for PumpSwap pool accounts.
//!
//! One handler keeps every PumpSwap pool account live in the cache
//! under the `account:Pool` Anchor discriminator. Downstream
//! consumers (executors, exit strategies, market-data analytics)
//! read pool state with sub-millisecond latency instead of paying
//! an RPC round-trip.
//!
//! Only compiled when the `cache-handlers` feature is enabled.

use std::collections::HashSet;
use std::sync::Arc;

use solana_program::pubkey::Pubkey;
use solana_protocols_macros::OnchainAccount;
use solana_account_traits::{CacheInsert, HandleResult, HandlerError, StorageHandler};

use super::constants::{POOL_DISCRIMINATOR, PROGRAM_ID};
use super::state::PumpSwapPool;

/// Handler for PumpSwap pool account updates.
///
/// Pool accounts contain everything needed to price a swap: base /
/// quote vaults, fee config, creator, LP supply. The parse-only half
/// (program id, discriminator, deserialize) + the `VerifiedDecoder` proof and
/// golden-fixture test are generated by [`OnchainAccount`]; only `apply` is
/// hand-written (it's cache-specific).
#[derive(Debug, Default, Clone, OnchainAccount)]
#[onchain(
    program = PROGRAM_ID,
    state = PumpSwapPool,
    discriminator_const = POOL_DISCRIMINATOR,
    decode = PumpSwapPool::from_account_data,
    fixture = "pumpswap/pool_v3_full_301.json"
)]
pub struct PumpSwapPoolHandler {
    /// Restricts vault subscriptions to these pools. `None` — the default —
    /// means **every** pool that updates gets its vaults tracked, which is what
    /// research wants: the tail of rarely-traded pools is the interesting part,
    /// and a watchlist truncates exactly it.
    ///
    /// History worth keeping, because the first two readings were wrong: an
    /// ungated run on 2026-08-10 collapsed ingestion ~20× (1,114 accounts
    /// applied vs 22,123, with 56,925 shed by the ordering worker). That was
    /// blamed first on vault *cardinality*, then on steady-state vault message
    /// *volume*. It was neither — it was ~240 serial blocking RPC round-trips
    /// per second from the ingest hot path, because vault dependencies were
    /// being RPC-fetched (un-deduplicated, once per pool update) instead of
    /// simply subscribed. With that fixed, subscribing all vaults costs only
    /// the account messages themselves.
    vault_watchlist: Option<Arc<HashSet<Pubkey>>>,
}

impl PumpSwapPoolHandler {
    /// Track vaults for every pool (see `vault_watchlist`).
    ///
    #[must_use]
    pub const fn new() -> Self {
        Self {
            vault_watchlist: None,
        }
    }

    /// Track vaults only for the pools in `watchlist`.
    ///
    /// A deliberate narrowing for consumers that price a known set and do not
    /// want the whole firehose's reserves.
    #[must_use]
    pub fn with_vault_watchlist(watchlist: Arc<HashSet<Pubkey>>) -> Self {
        Self {
            vault_watchlist: Some(watchlist),
        }
    }
}

impl<C> StorageHandler<C> for PumpSwapPoolHandler
where
    C: CacheInsert<Pubkey, PumpSwapPool> + Send + Sync + 'static,
{
    fn apply(
        &self,
        cache: &C,
        pubkey: &Pubkey,
        state: &Self::State,
        slot: u64,
    ) -> Result<HandleResult, HandlerError> {
        cache.insert(*pubkey, state.clone(), slot);
        // A PumpSwap pool holds no reserves inline — they live in these two
        // vault token accounts. For pools on the watchlist, report them as
        // dependencies so the ingest layer subscribes them; `TokenAccountHandler`
        // then keeps their balances live and the quoter reads
        // pool -> vaults -> reserves. `Dynamic`: a vault is a *token* account,
        // not owned by the pumpswap program, so no owner filter covers it — it
        // must be subscribed by pubkey, and never RPC-fetched.
        //
        // A watchlist, when set, narrows this to the pools it names.
        let watched = self
            .vault_watchlist
            .as_ref()
            .is_none_or(|w| w.contains(pubkey));
        if !watched {
            return Ok(HandleResult::default());
        }
        Ok(HandleResult {
            // Generated from PumpSwapQuote's field list — the same declaration
            // `assemble` reads, so what we keep live and what the quoter needs
            // cannot drift. Hand-listing them here is how an account gets added
            // to the quote and never subscribed, leaving the pool permanently
            // unquotable with no error anywhere.
            accounts_to_subscribe: super::quote::PumpSwapQuote::dependent_accounts(state),
            ..Default::default()
        })
    }
}
