//! PumpSwap pool state.
//!
//! The pool account stores the AMM state including reserves (via vault token accounts),
//! LP token info, and creator address. Unlike Pumpfun bonding curves, PumpSwap uses
//! standard constant product AMM with separate vault accounts.
//!
//! # Layout (fields span 244 bytes; trailing padding varies: 261/300/301-byte
//! variants observed on mainnet all share this layout — see `fixtures/pumpswap/`)
//!
//! | Offset | Size | Field |
//! |--------|------|-------|
//! | 0      | 8    | discriminator |
//! | 8      | 1    | bump |
//! | 9      | 2    | index |
//! | 11     | 32   | creator |
//! | 43     | 32   | base_mint |
//! | 75     | 32   | quote_mint |
//! | 107    | 32   | lp_mint |
//! | 139    | 32   | pool_base_token_account |
//! | 171    | 32   | pool_quote_token_account |
//! | 203    | 8    | lp_supply |
//! | 211    | 32   | coin_creator |
//! | 243    | 1    | is_mayhem_mode |
//! | 244    | 57   | padding |

use serde::{Deserialize, Serialize};
use solana_program::pubkey::Pubkey;
use solana_protocols_macros::OnchainState;

#[cfg(test)]
use super::constants::POOL_ACCOUNT_SIZE;
use super::constants::POOL_DISCRIMINATOR;
use crate::error::{Error, Result};

/// PumpSwap pool state from on-chain account.
///
/// Exactly the account's fields, in the account's order — the layout walk in
/// [`OnchainState`] is generated from this list, so a field the account does
/// not have cannot be added here. Reserves are *not* among them: PumpSwap
/// keeps them in two vault token accounts, and pairing the two is
/// [`PoolWithReserves`]'s job.
///
/// [`OnchainState`]: crate::parsing::state::OnchainState
#[derive(Debug, Clone, Default, Serialize, Deserialize, OnchainState)]
#[state(discriminator = POOL_DISCRIMINATOR)]
#[state(fixtures(
    "pumpswap/pool_v1_261.json",
    "pumpswap/pool_v2_300.json",
    "pumpswap/pool_v3_full_301.json"
))]
pub struct PumpSwapPool {
    /// PDA bump seed.
    pub bump: u8,
    /// Pool index.
    pub index: u16,
    /// Pool creator wallet.
    pub creator: Pubkey,
    /// Base token mint (meme token).
    pub base_mint: Pubkey,
    /// Quote token mint (typically WSOL).
    pub quote_mint: Pubkey,
    /// LP token mint.
    pub lp_mint: Pubkey,
    /// Pool's base token ATA.
    pub pool_base_token_account: Pubkey,
    /// Pool's quote token ATA.
    pub pool_quote_token_account: Pubkey,
    /// LP token supply.
    pub lp_supply: u64,
    /// Original coin creator.
    pub coin_creator: Pubkey,
    /// Whether mayhem mode is active.
    pub is_mayhem_mode: bool,
}

/// A pool paired with the vault balances the pool account does not carry.
///
/// PumpSwap keeps reserves in two vault token accounts, so no decode of the
/// pool account can supply them. They used to live on [`PumpSwapPool`] as
/// fields a `set_reserves` mutator filled in — which meant a pool read from
/// anywhere but the one caller that remembered reported `0 / 0`, and a zero
/// could not be told apart from a genuinely empty pool.
///
/// Here they are constructor arguments, so a bundle without them does not
/// exist. Mirrors `raydium_v4::PoolWithReserves`, which faced the same fact.
#[derive(Debug, Clone)]
pub struct PoolWithReserves {
    pool: PumpSwapPool,
    base_reserves: u64,
    quote_reserves: u64,
}

impl PoolWithReserves {
    /// Pair a decoded pool with the vault balances read alongside it.
    #[must_use]
    pub const fn new(pool: PumpSwapPool, base_reserves: u64, quote_reserves: u64) -> Self {
        Self {
            pool,
            base_reserves,
            quote_reserves,
        }
    }

    #[must_use]
    pub const fn pool(&self) -> &PumpSwapPool {
        &self.pool
    }

    #[must_use]
    pub const fn base_reserves(&self) -> u64 {
        self.base_reserves
    }

    #[must_use]
    pub const fn quote_reserves(&self) -> u64 {
        self.quote_reserves
    }

    /// Both sides funded — the pool can price a trade.
    #[must_use]
    pub const fn is_active(&self) -> bool {
        self.base_reserves > 0 && self.quote_reserves > 0
    }

    /// Spot price in SOL per token (UI units), assuming a WSOL quote side.
    #[must_use]
    pub fn spot_price(&self) -> f64 {
        if self.base_reserves == 0 || self.quote_reserves == 0 {
            return 0.0;
        }
        let quote_ui = self.quote_reserves as f64 / 1e9; // SOL
        let base_ui = self.base_reserves as f64 / 1e6; // tokens
        quote_ui / base_ui
    }
}

impl PumpSwapPool {
    /// Parse pool state from on-chain account data, in this crate's error type.
    ///
    /// The layout walk is generated by [`OnchainState`] from the field list —
    /// including the required length, which is why no `POOL_MIN_SIZE` constant
    /// is consulted here. The hand-written gate used to read `>= 301` against a
    /// true field span of 244, rejecting the majority of real pools.
    ///
    /// [`OnchainState`]: crate::parsing::state::OnchainState
    pub fn from_account_data(data: &[u8]) -> Result<Self> {
        <Self as crate::parsing::state::OnchainState>::from_account_data(data)
            .map_err(|e| Error::parse_error(format!("PumpSwap pool: {e}")))
    }

    /// Check if this pool has a creator (non-default pubkey).
    #[must_use]
    pub fn has_creator(&self) -> bool {
        self.coin_creator != Pubkey::default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_pool_data() -> Vec<u8> {
        let mut data = vec![0u8; POOL_ACCOUNT_SIZE];
        // The real discriminator: the parse validates it now, rather than
        // trusting that a registry routed us here.
        data[0..8].copy_from_slice(&POOL_DISCRIMINATOR);
        // bump = 255
        data[8] = 255;
        // index = 42
        data[9..11].copy_from_slice(&42u16.to_le_bytes());
        // Leave pubkeys as zeros for simplicity
        // lp_supply = 1000
        data[203..211].copy_from_slice(&1000u64.to_le_bytes());
        // is_mayhem_mode = false
        data[243] = 0;
        data
    }

    #[test]
    fn parse_pool_state() {
        let data = make_test_pool_data();
        let pool = PumpSwapPool::from_account_data(&data).unwrap();

        assert_eq!(pool.bump, 255);
        assert_eq!(pool.index, 42);
        assert_eq!(pool.lp_supply, 1000);
        assert!(!pool.is_mayhem_mode);
    }

    #[test]
    fn parse_rejects_short_data() {
        let data = vec![0u8; 100];
        assert!(PumpSwapPool::from_account_data(&data).is_err());
    }

    /// Every observed on-chain pool size (301/300/261) decodes at the same field
    /// offsets against real frozen bytes. This is the layout-truth check that the
    /// old `< 301` gate never had — it silently rejected the 300/261-byte
    /// variants (the majority of pools) even though every field is present.
    #[test]
    fn decodes_all_onchain_pool_variants() {
        for fx_name in [
            "pumpswap/pool_v3_full_301.json",
            "pumpswap/pool_v2_300.json",
            "pumpswap/pool_v1_261.json",
        ] {
            let fx = crate::test_fixtures::AccountFixture::load(fx_name);
            let pool = PumpSwapPool::from_account_data(fx.data())
                .unwrap_or_else(|e| panic!("{fx_name}: {e}"));
            fx.assert_matches(&pool);
        }
    }

    #[test]
    fn pool_with_reserves() {
        let data = make_test_pool_data();
        let pool = PoolWithReserves::new(
            PumpSwapPool::from_account_data(&data).unwrap(),
            1_000_000_000_000, // 1M tokens
            85_000_000_000,    // 85 SOL
        );

        assert!(pool.is_active());
        assert!(pool.spot_price() > 0.0);

        // spot_price = (85 SOL) / (1M tokens) = 0.000085 SOL per token
        let expected = 85.0 / 1_000_000.0;
        assert!((pool.spot_price() - expected).abs() < 1e-10);
    }

    #[test]
    fn pool_inactive_without_reserves() {
        // Reserves can no longer be *omitted* — the bundle demands them — so
        // the case this guards is an genuinely empty pool, which is now
        // distinguishable from an unfilled one at the construction site.
        let data = make_test_pool_data();
        let pool = PoolWithReserves::new(PumpSwapPool::from_account_data(&data).unwrap(), 0, 0);

        assert!(!pool.is_active());
        assert_eq!(pool.spot_price(), 0.0);
    }
}
