//! PumpSwap buy instruction types and builder.
//!
//! Account layout from PumpSwap IDL (pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA).
//! Field order = on-chain account order.

use serde::{Deserialize, Serialize};
use solana_program::pubkey::Pubkey;
use solana_protocols_macros::{AccountMetas, InstructionData, OnchainInstruction};
use solana_sdk::instruction::Instruction;

use super::super::accounts::PumpSwapKeys;
use super::super::constants::{
    BUY_DISCRIMINATOR, BUY_EXACT_QUOTE_IN_DISCRIMINATOR, EVENT_AUTHORITY, FEE_CONFIG, FEE_PROGRAM,
    GLOBAL_CONFIG, GLOBAL_VOLUME_ACCUMULATOR, PROGRAM_ID, PROTOCOL_FEE_RECIPIENT,
    PROTOCOL_FEE_RECIPIENT_TOKEN_ACCOUNT,
};
use crate::error::Result;
use crate::traits::InstructionBuilder;

/// PumpSwap buy instruction accounts.
///
/// `FromAccountKeys` is auto-generated by `#[derive(AccountMetas)]`;
/// `OnchainInstruction` adds a golden round-trip test against a real buy.
#[derive(Debug, Clone, AccountMetas, OnchainInstruction)]
#[idl(program = "pump_amm", instruction = "buy")]
#[onchain_ix(fixture = "pumpswap/ix_buy.json")]
pub struct BuyAccounts {
    /// Pool state account.
    #[account(writable)]
    pub pool: Pubkey,
    /// User wallet (signer).
    #[account(writable, signer)]
    pub user: Pubkey,
    /// PumpSwap global configuration.
    #[account]
    pub global_config: Pubkey,
    /// Base token mint (the meme token).
    #[account]
    pub base_mint: Pubkey,
    /// Quote token mint (WSOL).
    #[account]
    pub quote_mint: Pubkey,
    /// User's base token account.
    #[account(writable)]
    pub user_base_token_account: Pubkey,
    /// User's quote token account.
    #[account(writable)]
    pub user_quote_token_account: Pubkey,
    /// Pool's base token vault.
    #[account(writable)]
    pub pool_base_token_account: Pubkey,
    /// Pool's quote token vault.
    #[account(writable)]
    pub pool_quote_token_account: Pubkey,
    /// Protocol fee recipient.
    #[account]
    pub protocol_fee_recipient: Pubkey,
    /// Protocol fee recipient token account.
    #[account(writable)]
    pub protocol_fee_recipient_token_account: Pubkey,
    /// Base token program (SPL Token or Token-2022).
    #[account]
    pub base_token_program: Pubkey,
    /// Quote token program.
    #[account]
    pub quote_token_program: Pubkey,
    /// System program.
    #[account]
    pub system_program: Pubkey,
    /// Associated token program.
    #[account]
    pub associated_token_program: Pubkey,
    /// Event authority PDA.
    #[account]
    pub event_authority: Pubkey,
    /// PumpSwap program.
    #[account]
    pub program: Pubkey,
    /// Creator vault ATA (receives creator fees).
    #[account(writable)]
    pub coin_creator_vault_ata: Pubkey,
    /// Creator vault authority PDA.
    #[account]
    pub coin_creator_vault_authority: Pubkey,
    /// Global volume accumulator PDA.
    #[account]
    pub global_volume_accumulator: Pubkey,
    /// User volume accumulator PDA.
    #[account(writable)]
    pub user_volume_accumulator: Pubkey,
    /// Fee config PDA.
    #[account]
    pub fee_config: Pubkey,
    /// Fee program.
    #[account]
    pub fee_program: Pubkey,
}

impl BuyAccounts {
    /// Create buy accounts from pool keys and user wallet.
    #[must_use]
    pub fn from_keys(keys: &PumpSwapKeys, user: &Pubkey) -> Self {
        BuyAccounts {
            pool: keys.pool,
            user: *user,
            global_config: GLOBAL_CONFIG,
            base_mint: keys.base_mint,
            quote_mint: keys.quote_mint,
            user_base_token_account: keys.user_base_ata(user),
            user_quote_token_account: keys.user_quote_ata(user),
            pool_base_token_account: keys.pool_base_token_account,
            pool_quote_token_account: keys.pool_quote_token_account,
            protocol_fee_recipient: PROTOCOL_FEE_RECIPIENT,
            protocol_fee_recipient_token_account: PROTOCOL_FEE_RECIPIENT_TOKEN_ACCOUNT,
            base_token_program: spl_token::id(),
            quote_token_program: spl_token::id(),
            system_program: solana_program::system_program::id(),
            associated_token_program: spl_associated_token_account::id(),
            event_authority: EVENT_AUTHORITY,
            program: PROGRAM_ID,
            coin_creator_vault_ata: keys.creator_vault_ata,
            coin_creator_vault_authority: keys.creator_vault_authority,
            global_volume_accumulator: GLOBAL_VOLUME_ACCUMULATOR,
            user_volume_accumulator: keys.user_volume_accumulator(user),
            fee_config: FEE_CONFIG,
            fee_program: FEE_PROGRAM,
        }
    }
}

/// PumpSwap buy instruction parameters.
///
/// `FromInstructionData` is auto-generated by `#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, InstructionData)]`.
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    borsh::BorshDeserialize,
    borsh::BorshSerialize,
    InstructionData,
)]
#[instruction_data(discriminator = BUY_DISCRIMINATOR)]
pub struct BuyParams {
    /// Minimum base tokens to receive.
    pub base_amount_out: u64,
    /// Maximum quote (SOL) to spend.
    pub max_quote_amount_in: u64,
    /// Trailing `OptionBool` the IDL declares. Carried, not dropped: the flag
    /// changes which accounts the program expects, and a builder that omits it
    /// can emit an instruction whose accounts contradict its own arguments.
    pub track_volume: crate::protocols::OptionBool,
}

/// PumpSwap `buy_exact_quote_in` parameters.
///
/// Mirror image of [`BuyParams`]: the trader pins the quote spent rather than
/// the base received. Executed amounts still come from the emitted `BuyEvent`,
/// so extraction is shared — these params are slippage bounds, as ever.
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    borsh::BorshDeserialize,
    borsh::BorshSerialize,
    InstructionData,
)]
#[instruction_data(discriminator = BUY_EXACT_QUOTE_IN_DISCRIMINATOR)]
pub struct BuyExactQuoteInParams {
    /// Quote (SOL) the trader is willing to spend — the pinned side.
    pub spendable_quote_in: u64,
    /// Minimum base tokens to accept.
    pub min_base_amount_out: u64,
    /// Trailing `OptionBool` — see [`BuyParams::track_volume`].
    pub track_volume: crate::protocols::OptionBool,
}

/// `buy_exact_quote_in` uses the same accounts as `buy`.
pub type BuyExactQuoteInAccounts = BuyAccounts;

impl BuyParams {
    /// Create new buy parameters.
    #[must_use]
    pub fn new(base_amount_out: u64, max_quote_amount_in: u64) -> Self {
        Self {
            base_amount_out,
            max_quote_amount_in,
            // Absent serialises to nothing, so what we emit is unchanged from
            // before this field existed. Opt in deliberately.
            track_volume: crate::protocols::OptionBool::None,
        }
    }

    /// Set the trailing `OptionBool`.
    ///
    /// Separate from [`new`](Self::new) because it is not a free parameter: it
    /// changes the account list the program requires.
    #[must_use]
    pub fn with_track_volume(mut self, track_volume: crate::protocols::OptionBool) -> Self {
        self.track_volume = track_volume;
        self
    }

    /// Create buy parameters from swap output with slippage.
    ///
    /// # Arguments
    /// * `tokens_out` - Expected tokens from swap calculation
    /// * `sol_in` - SOL amount from swap calculation
    /// * `slippage_bps` - Slippage tolerance in basis points
    #[must_use]
    pub fn from_swap_output(tokens_out: u64, sol_in: u64, slippage_bps: u16) -> Self {
        let min_tokens = (tokens_out as u128 * (10000 - slippage_bps as u128) / 10000) as u64;
        let max_sol = (sol_in as u128 * (10000 + slippage_bps as u128) / 10000) as u64;

        BuyParams {
            base_amount_out: min_tokens,
            max_quote_amount_in: max_sol,
            track_volume: crate::protocols::OptionBool::None,
        }
    }
}

/// Builder for PumpSwap buy instructions.
pub struct BuyBuilder;

impl InstructionBuilder for BuyBuilder {
    type Keys = PumpSwapKeys;
    type Params = BuyParams;

    fn build_swap_instruction(
        keys: &Self::Keys,
        user: &Pubkey,
        params: Self::Params,
    ) -> Result<Instruction> {
        let accounts = BuyAccounts::from_keys(keys, user);

        Ok(Instruction {
            program_id: PROGRAM_ID,
            accounts: accounts.to_account_metas(),
            data: params.to_data(),
        })
    }

    fn build_swap_with_setup(
        keys: &Self::Keys,
        user: &Pubkey,
        params: Self::Params,
        create_ata: bool,
    ) -> Result<Vec<Instruction>> {
        let mut instructions = Vec::with_capacity(2);

        if create_ata {
            // Create user's base token ATA (meme token) if it doesn't exist
            let ata_ix = spl_associated_token_account::instruction::create_associated_token_account_idempotent(
                user,
                user,
                &keys.base_mint,
                &spl_token::id(),
            );
            instructions.push(ata_ix);
        }

        instructions.push(Self::build_swap_instruction(keys, user, params)?);

        Ok(instructions)
    }
}

impl BuyBuilder {
    /// Convenience method to build buy instruction directly.
    #[must_use]
    pub fn build(
        keys: &PumpSwapKeys,
        user: &Pubkey,
        base_amount_out: u64,
        max_quote_amount_in: u64,
    ) -> Instruction {
        Self::build_swap_instruction(
            keys,
            user,
            BuyParams::new(base_amount_out, max_quote_amount_in),
        )
        .expect("BuyBuilder::build_swap_instruction should not fail")
    }

    /// Build buy instruction with ATA creation.
    #[must_use]
    pub fn build_with_ata(
        keys: &PumpSwapKeys,
        user: &Pubkey,
        base_amount_out: u64,
        max_quote_amount_in: u64,
    ) -> Vec<Instruction> {
        Self::build_swap_with_setup(
            keys,
            user,
            BuyParams::new(base_amount_out, max_quote_amount_in),
            true,
        )
        .expect("BuyBuilder::build_swap_with_setup should not fail")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parsing::FromInstructionData;

    fn make_test_keys() -> PumpSwapKeys {
        PumpSwapKeys::new(
            Pubkey::new_unique(), // pool
            Pubkey::new_unique(), // base_mint
            Pubkey::new_unique(), // quote_mint
            Pubkey::new_unique(), // pool_base
            Pubkey::new_unique(), // pool_quote
            Pubkey::new_unique(), // coin_creator
        )
    }

    #[test]
    fn buy_params_roundtrip() {
        let params = BuyParams::new(1_000_000, 500_000_000);
        let data = params.to_data();

        assert_eq!(data.len(), 24); // 8 disc + 8 + 8
        assert_eq!(&data[..8], &BUY_DISCRIMINATOR);

        // Parse back (skip discriminator per trait contract)
        let parsed = BuyParams::from_instruction_data(&data[8..]).unwrap();
        assert_eq!(parsed.base_amount_out, 1_000_000);
        assert_eq!(parsed.max_quote_amount_in, 500_000_000);
    }

    #[test]
    fn buy_params_from_swap_output() {
        let params = BuyParams::from_swap_output(1_000_000, 100_000_000, 100); // 1% slippage

        assert_eq!(params.base_amount_out, 990_000);
        assert_eq!(params.max_quote_amount_in, 101_000_000);
    }

    #[test]
    fn buy_accounts_count() {
        assert_eq!(BuyAccounts::ACCOUNT_COUNT, 23);
    }

    #[test]
    fn buy_builder_creates_instruction() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let ix = BuyBuilder::build(&keys, &user, 1_000_000, 500_000_000);

        assert_eq!(ix.program_id, PROGRAM_ID);
        assert_eq!(ix.accounts.len(), 23);
        assert!(!ix.data.is_empty());

        // Verify user is a signer
        let user_account = ix.accounts.iter().find(|a| a.pubkey == user);
        assert!(user_account.is_some());
        assert!(user_account.unwrap().is_signer);
    }

    #[test]
    fn buy_with_ata_creates_two_instructions() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let instructions = BuyBuilder::build_with_ata(&keys, &user, 1_000_000, 500_000_000);

        assert_eq!(instructions.len(), 2);
        assert_eq!(
            instructions[0].program_id,
            spl_associated_token_account::id()
        );
        assert_eq!(instructions[1].program_id, PROGRAM_ID);
    }

    #[test]
    fn buy_accounts_from_keys() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let accounts = BuyAccounts::from_keys(&keys, &user);

        assert_eq!(accounts.pool, keys.pool);
        assert_eq!(accounts.user, user);
        assert_eq!(accounts.base_mint, keys.base_mint);
        assert_eq!(accounts.quote_mint, keys.quote_mint);
        assert_eq!(
            accounts.pool_base_token_account,
            keys.pool_base_token_account
        );
        assert_eq!(
            accounts.pool_quote_token_account,
            keys.pool_quote_token_account
        );
        assert_eq!(accounts.coin_creator_vault_ata, keys.creator_vault_ata);
        assert_eq!(
            accounts.coin_creator_vault_authority,
            keys.creator_vault_authority
        );
        assert_eq!(accounts.global_config, GLOBAL_CONFIG);
        assert_eq!(accounts.event_authority, EVENT_AUTHORITY);
    }
}
