//! PumpSwap sell instruction types and builder.
//!
//! Account layout from PumpSwap IDL (pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA).
//! Field order = on-chain account order.

use serde::{Deserialize, Serialize};
use solana_program::pubkey::Pubkey;
use solana_protocols_macros::{AccountMetas, InstructionData, OnchainInstruction};
use solana_sdk::instruction::Instruction;

use super::super::accounts::PumpSwapKeys;
use super::super::constants::{
    EVENT_AUTHORITY, FEE_CONFIG, FEE_PROGRAM, GLOBAL_CONFIG, PROGRAM_ID, PROTOCOL_FEE_RECIPIENT,
    PROTOCOL_FEE_RECIPIENT_TOKEN_ACCOUNT, SELL_DISCRIMINATOR,
};
use crate::error::Result;
use crate::traits::InstructionBuilder;

/// PumpSwap sell instruction accounts.
///
/// Sell has fewer accounts than Buy — no volume accumulators.
/// `FromAccountKeys` is auto-generated by `#[derive(AccountMetas)]`;
/// `OnchainInstruction` adds a golden round-trip test against a real sell.
#[derive(Debug, Clone, AccountMetas, OnchainInstruction)]
#[idl(program = "pump_amm", instruction = "sell")]
#[onchain_ix(fixture = "pumpswap/ix_sell.json")]
pub struct SellAccounts {
    /// Pool state account.
    #[account(writable)]
    pub pool: Pubkey,
    /// User wallet (signer).
    #[account(writable, signer)]
    pub user: Pubkey,
    /// PumpSwap global configuration.
    #[account]
    pub global_config: Pubkey,
    /// Base token mint (the meme token).
    #[account]
    pub base_mint: Pubkey,
    /// Quote token mint (WSOL).
    #[account]
    pub quote_mint: Pubkey,
    /// User's base token account.
    #[account(writable)]
    pub user_base_token_account: Pubkey,
    /// User's quote token account.
    #[account(writable)]
    pub user_quote_token_account: Pubkey,
    /// Pool's base token vault.
    #[account(writable)]
    pub pool_base_token_account: Pubkey,
    /// Pool's quote token vault.
    #[account(writable)]
    pub pool_quote_token_account: Pubkey,
    /// Protocol fee recipient.
    #[account]
    pub protocol_fee_recipient: Pubkey,
    /// Protocol fee recipient token account.
    #[account(writable)]
    pub protocol_fee_recipient_token_account: Pubkey,
    /// Base token program (SPL Token or Token-2022).
    #[account]
    pub base_token_program: Pubkey,
    /// Quote token program.
    #[account]
    pub quote_token_program: Pubkey,
    /// System program.
    #[account]
    pub system_program: Pubkey,
    /// Associated token program.
    #[account]
    pub associated_token_program: Pubkey,
    /// Event authority PDA.
    #[account]
    pub event_authority: Pubkey,
    /// PumpSwap program.
    #[account]
    pub program: Pubkey,
    /// Creator vault ATA (receives creator fees).
    #[account(writable)]
    pub coin_creator_vault_ata: Pubkey,
    /// Creator vault authority PDA.
    #[account]
    pub coin_creator_vault_authority: Pubkey,
    /// Fee config PDA.
    #[account]
    pub fee_config: Pubkey,
    /// Fee program.
    #[account]
    pub fee_program: Pubkey,
}

impl SellAccounts {
    /// Create sell accounts from pool keys and user wallet.
    #[must_use]
    pub fn from_keys(keys: &PumpSwapKeys, user: &Pubkey) -> Self {
        SellAccounts {
            pool: keys.pool,
            user: *user,
            global_config: GLOBAL_CONFIG,
            base_mint: keys.base_mint,
            quote_mint: keys.quote_mint,
            user_base_token_account: keys.user_base_ata(user),
            user_quote_token_account: keys.user_quote_ata(user),
            pool_base_token_account: keys.pool_base_token_account,
            pool_quote_token_account: keys.pool_quote_token_account,
            protocol_fee_recipient: PROTOCOL_FEE_RECIPIENT,
            protocol_fee_recipient_token_account: PROTOCOL_FEE_RECIPIENT_TOKEN_ACCOUNT,
            base_token_program: spl_token::id(),
            quote_token_program: spl_token::id(),
            system_program: solana_program::system_program::id(),
            associated_token_program: spl_associated_token_account::id(),
            event_authority: EVENT_AUTHORITY,
            program: PROGRAM_ID,
            coin_creator_vault_ata: keys.creator_vault_ata,
            coin_creator_vault_authority: keys.creator_vault_authority,
            fee_config: FEE_CONFIG,
            fee_program: FEE_PROGRAM,
        }
    }
}

/// PumpSwap sell instruction parameters.
///
/// `FromInstructionData` is auto-generated by `#[derive(InstructionData)]`.
#[derive(Debug, Clone, Serialize, Deserialize, InstructionData)]
#[instruction_data(discriminator = SELL_DISCRIMINATOR)]
pub struct SellParams {
    /// Base tokens to sell.
    pub base_amount_in: u64,
    /// Minimum quote (SOL) to receive.
    pub min_quote_amount_out: u64,
}

impl SellParams {
    /// Create new sell parameters.
    #[must_use]
    pub fn new(base_amount_in: u64, min_quote_amount_out: u64) -> Self {
        Self {
            base_amount_in,
            min_quote_amount_out,
        }
    }

    /// Create sell parameters from swap output with slippage.
    ///
    /// # Arguments
    /// * `tokens_in` - Tokens to sell
    /// * `sol_out` - Expected SOL from swap calculation
    /// * `slippage_bps` - Slippage tolerance in basis points
    #[must_use]
    pub fn from_swap_output(tokens_in: u64, sol_out: u64, slippage_bps: u16) -> Self {
        let min_sol = (sol_out as u128 * (10000 - slippage_bps as u128) / 10000) as u64;

        SellParams {
            base_amount_in: tokens_in,
            min_quote_amount_out: min_sol,
        }
    }
}

/// Builder for PumpSwap sell instructions.
pub struct SellBuilder;

impl InstructionBuilder for SellBuilder {
    type Keys = PumpSwapKeys;
    type Params = SellParams;

    fn build_swap_instruction(
        keys: &Self::Keys,
        user: &Pubkey,
        params: Self::Params,
    ) -> Result<Instruction> {
        let accounts = SellAccounts::from_keys(keys, user);

        Ok(Instruction {
            program_id: PROGRAM_ID,
            accounts: accounts.to_account_metas(),
            data: params.to_data(),
        })
    }
}

impl SellBuilder {
    /// Convenience method to build sell instruction directly.
    #[must_use]
    pub fn build(
        keys: &PumpSwapKeys,
        user: &Pubkey,
        base_amount_in: u64,
        min_quote_amount_out: u64,
    ) -> Instruction {
        Self::build_swap_instruction(
            keys,
            user,
            SellParams::new(base_amount_in, min_quote_amount_out),
        )
        .expect("SellBuilder::build_swap_instruction should not fail")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parsing::FromInstructionData;

    fn make_test_keys() -> PumpSwapKeys {
        PumpSwapKeys::new(
            Pubkey::new_unique(),
            Pubkey::new_unique(),
            Pubkey::new_unique(),
            Pubkey::new_unique(),
            Pubkey::new_unique(),
            Pubkey::new_unique(),
        )
    }

    #[test]
    fn sell_params_roundtrip() {
        let params = SellParams::new(1_000_000, 400_000_000);
        let data = params.to_data();

        assert_eq!(data.len(), 24); // 8 disc + 8 + 8
        assert_eq!(&data[..8], &SELL_DISCRIMINATOR);

        // Parse back (skip discriminator per trait contract)
        let parsed = SellParams::from_instruction_data(&data[8..]).unwrap();
        assert_eq!(parsed.base_amount_in, 1_000_000);
        assert_eq!(parsed.min_quote_amount_out, 400_000_000);
    }

    #[test]
    fn sell_params_from_swap_output() {
        let params = SellParams::from_swap_output(1_000_000, 100_000_000, 100); // 1% slippage

        assert_eq!(params.base_amount_in, 1_000_000);
        assert_eq!(params.min_quote_amount_out, 99_000_000);
    }

    #[test]
    fn sell_accounts_count() {
        assert_eq!(SellAccounts::ACCOUNT_COUNT, 21);
    }

    #[test]
    fn sell_builder_creates_instruction() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let ix = SellBuilder::build(&keys, &user, 1_000_000, 400_000_000);

        assert_eq!(ix.program_id, PROGRAM_ID);
        assert_eq!(ix.accounts.len(), 21);
        assert!(!ix.data.is_empty());

        let user_account = ix.accounts.iter().find(|a| a.pubkey == user);
        assert!(user_account.is_some());
        assert!(user_account.unwrap().is_signer);
    }

    #[test]
    fn sell_accounts_from_keys() {
        let keys = make_test_keys();
        let user = Pubkey::new_unique();

        let accounts = SellAccounts::from_keys(&keys, &user);

        assert_eq!(accounts.pool, keys.pool);
        assert_eq!(accounts.user, user);
        assert_eq!(accounts.coin_creator_vault_ata, keys.creator_vault_ata);
        assert_eq!(
            accounts.coin_creator_vault_authority,
            keys.creator_vault_authority
        );
    }
}
