//! Pump.fun bonding curve account state.
//!
//! Multiple on-chain layouts are live at the same time due to program
//! upgrades. Every variant shares the same **core 81-byte prefix**:
//!
//! | offset | size | field                    |
//! |--------|------|--------------------------|
//! | 0      | 8    | Anchor discriminator     |
//! | 8      | 8    | `virtual_token_reserves` |
//! | 16     | 8    | `virtual_sol_reserves`   |
//! | 24     | 8    | `real_token_reserves`    |
//! | 32     | 8    | `real_sol_reserves`      |
//! | 40     | 8    | `token_total_supply`     |
//! | 48     | 1    | `complete` (0 or 1)      |
//! | 49     | 32   | `creator` (Pubkey)       |
//!
//! The **cashback upgrade** (83-byte variant) adds two trailing bools:
//!
//! | offset | size | field              |
//! |--------|------|--------------------|
//! | 81     | 1    | `is_mayhem_mode`   |
//! | 82     | 1    | `is_cashback_coin` |
//!
//! The **post-upgrade 150/151-byte variants** reserve additional trailing
//! bytes for future use. We read the two cashback bools if present and
//! ignore the rest — the meaningful fields for quoting are all within
//! the first 83 bytes.

use solana_program::pubkey::Pubkey;

use crate::error::{Error, Result};

use solana_protocols_macros::OnchainState;

use crate::parsing::state::Legacy;

use super::constants::{BONDING_CURVE_DISCRIMINATOR, SOL_DECIMALS, TOKEN_DECIMALS};

/// On-chain Pump.fun bonding curve account state.
///
/// The field list *is* the layout — `#[derive(OnchainState)]` walks it to
/// generate the parse and to derive [`REQUIRED_LEN`], so no size constant is
/// transcribed and no field the account lacks can be added.
///
/// [`REQUIRED_LEN`]: crate::parsing::state::OnchainState::REQUIRED_LEN
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, OnchainState)]
#[state(discriminator = BONDING_CURVE_DISCRIMINATOR)]
#[state(fixtures("pumpfun/bonding_curve_150.json"))]
pub struct BondingCurve {
    pub virtual_token_reserves: u64,
    pub virtual_sol_reserves: u64,
    pub real_token_reserves: u64,
    pub real_sol_reserves: u64,
    pub token_total_supply: u64,
    pub complete: bool,
    pub creator: Pubkey,
    /// Added in the cashback program upgrade.
    ///
    /// [`Legacy::Absent`] means the account predates it (the core 81-byte
    /// layout) — which is **not** the same fact as `Present(false)`. Callers decide what an
    /// unmigrated curve means for them; collapsing the two here would destroy
    /// the distinction before anyone could act on it.
    #[state(added_in = "cashback")]
    pub is_mayhem_mode: Legacy<bool>,
    /// Added in the cashback program upgrade. See [`is_mayhem_mode`].
    ///
    /// [`is_mayhem_mode`]: Self::is_mayhem_mode
    #[state(added_in = "cashback")]
    pub is_cashback_coin: Legacy<bool>,
}

impl BondingCurve {
    /// Parse from raw account bytes (Anchor-discriminator prefix included).
    ///
    /// Requires the 81-byte core prefix (8 disc + reserves + complete +
    /// creator). The two cashback flag bytes at offsets 81 / 82 are read
    /// optionally and default to `false` when absent. Any further
    /// trailing bytes (the 150 / 151-byte post-upgrade layouts, and any
    /// future variant) are ignored — Pumpfun reserves that space for
    /// fields that aren't meaningful for quoting.
    ///
    /// Discriminator validation happens one layer up at the registry —
    /// here we trust the caller dispatched us because the discriminator
    /// matched.
    /// Parse from raw account bytes, in this crate's error type.
    ///
    /// The layout walk itself is generated by [`OnchainState`]; this only
    /// adapts the error so existing callers are unaffected.
    ///
    /// [`OnchainState`]: crate::parsing::state::OnchainState
    pub fn from_account_data(data: &[u8]) -> Result<Self> {
        <Self as crate::parsing::state::OnchainState>::from_account_data(data).map_err(
            |e| match e {
                crate::parsing::state::AccountParseError::TooShort { len, need } => {
                    Error::AccountDataTooShort {
                        expected: need,
                        actual: len,
                    }
                }
                other => Error::invalid_account_data(other.to_string()),
            },
        )
    }

    /// Current spot price in SOL per token (UI units).
    #[must_use]
    pub fn spot_price(&self) -> f64 {
        if self.virtual_token_reserves == 0 {
            return 0.0;
        }
        let sol_ui = self.virtual_sol_reserves as f64 / 10f64.powi(SOL_DECIMALS as i32);
        let token_ui = self.virtual_token_reserves as f64 / 10f64.powi(TOKEN_DECIMALS as i32);
        sol_ui / token_ui
    }

    /// Whether this bonding curve is still live (`complete == false`).
    #[must_use]
    pub fn is_active(&self) -> bool {
        !self.complete
    }
}

#[cfg(test)]
mod tests {
    use super::super::constants::BONDING_CURVE_DISCRIMINATOR;
    use super::*;

    /// A real mainnet bonding curve decodes to the field values an independent
    /// (python) decode of the same frozen bytes produced — a two-implementation
    /// cross-check of the hand-rolled offset reads against the chain.
    #[test]
    fn decodes_onchain_bonding_curve() {
        let fx = crate::test_fixtures::AccountFixture::load("pumpfun/bonding_curve_150.json");
        let bc = BondingCurve::from_account_data(fx.data()).expect("decode real bonding curve");
        fx.assert_matches(&bc);
    }

    fn sample() -> BondingCurve {
        BondingCurve {
            virtual_token_reserves: 1_000_000_000_000_000,
            virtual_sol_reserves: 30_000_000_000,
            real_token_reserves: 800_000_000_000_000,
            real_sol_reserves: 0,
            token_total_supply: 1_000_000_000_000_000,
            complete: false,
            creator: Pubkey::new_unique(),
            is_mayhem_mode: Legacy::Present(false),
            is_cashback_coin: Legacy::Present(false),
        }
    }

    /// Encode the **legacy 81-byte** layout (pre-cashback-upgrade).
    fn encode_81(curve: &BondingCurve) -> Vec<u8> {
        let mut data = Vec::with_capacity(81);
        data.extend_from_slice(&BONDING_CURVE_DISCRIMINATOR);
        data.extend_from_slice(&curve.virtual_token_reserves.to_le_bytes());
        data.extend_from_slice(&curve.virtual_sol_reserves.to_le_bytes());
        data.extend_from_slice(&curve.real_token_reserves.to_le_bytes());
        data.extend_from_slice(&curve.real_sol_reserves.to_le_bytes());
        data.extend_from_slice(&curve.token_total_supply.to_le_bytes());
        data.push(if curve.complete { 1 } else { 0 });
        data.extend_from_slice(curve.creator.as_ref());
        data
    }

    /// Encode the **83-byte cashback** layout.
    fn encode_83(curve: &BondingCurve) -> Vec<u8> {
        let mut data = encode_81(curve);
        // This layout is *defined* by carrying the flags, so absence here is a
        // caller error, not a version — encode_81 is the layout without them.
        data.push(u8::from(match curve.is_mayhem_mode {
            Legacy::Present(v) => v,
            Legacy::Absent => panic!("83-byte layout carries is_mayhem_mode"),
        }));
        data.push(u8::from(match curve.is_cashback_coin {
            Legacy::Present(v) => v,
            Legacy::Absent => panic!("83-byte layout carries is_cashback_coin"),
        }));
        data
    }

    /// Encode with arbitrary trailing zero bytes — models the 150 / 151
    /// layouts where Pumpfun reserves trailing space we don't parse.
    fn encode_padded(curve: &BondingCurve, total_len: usize) -> Vec<u8> {
        let mut data = encode_83(curve);
        data.resize(total_len, 0);
        data
    }

    #[test]
    fn from_account_data_roundtrip_81_legacy_reports_cashback_flags_absent() {
        let mut curve = sample();
        // The 81-byte layout predates the cashback upgrade, so the flags are
        // absent — `None`, never `Some(false)`. A parser that defaulted them
        // would make an unmigrated curve indistinguishable from a migrated one
        // whose flags happen to be off.
        curve.is_mayhem_mode = Legacy::Absent;
        curve.is_cashback_coin = Legacy::Absent;
        let data = encode_81(&curve);
        assert_eq!(data.len(), 81);
        let parsed = BondingCurve::from_account_data(&data).unwrap();
        assert_eq!(parsed, curve);
    }

    #[test]
    fn from_account_data_roundtrip_83_carries_cashback_flags() {
        let mut curve = sample();
        curve.is_mayhem_mode = Legacy::Present(true);
        curve.is_cashback_coin = Legacy::Present(true);
        let data = encode_83(&curve);
        assert_eq!(data.len(), 83);
        let parsed = BondingCurve::from_account_data(&data).unwrap();
        assert_eq!(parsed, curve);
    }

    #[test]
    fn from_account_data_accepts_any_trailing_padding_size() {
        // Registry gates on the discriminator; here we just accept any
        // variant that carries the 81-byte core. Exercise a spread of
        // sizes including the 150/151 Pumpfun has shipped, a random
        // larger size, and the boundary at 83.
        let mut curve = sample();
        curve.is_mayhem_mode = Legacy::Present(true);
        curve.is_cashback_coin = Legacy::Present(false);

        for len in [83, 128, 150, 151, 200, 256, 512] {
            let data = encode_padded(&curve, len);
            assert_eq!(data.len(), len);
            let parsed = BondingCurve::from_account_data(&data).unwrap();
            assert_eq!(parsed, curve, "len={len}");
        }
    }

    #[test]
    fn from_account_data_rejects_too_short_inputs() {
        // Any size below the 81-byte core is invalid — we can't read
        // the required reserves + creator fields.
        for len in [0usize, 10, 40, 80] {
            let err = BondingCurve::from_account_data(&vec![0u8; len]).unwrap_err();
            assert!(
                matches!(err, Error::AccountDataTooShort { .. }),
                "expected AccountDataTooShort at len={len}, got {err:?}"
            );
        }
    }

    /// The derived `REQUIRED_LEN` must equal the constant it replaced.
    ///
    /// `BONDING_CURVE_ACCOUNT_SIZE` was hand-summed (`8+8+8+8+8+8+1+32`). The
    /// derive computes the same figure from the field types, which is the
    /// point: a transcribed size is what made `POOL_ACCOUNT_SIZE = 301` reject
    /// the majority of real PumpSwap pools. Validated against the known-good
    /// value rather than trusted.
    #[test]
    fn derived_required_len_matches_the_hand_written_constant() {
        use crate::parsing::state::OnchainState;
        assert_eq!(
            <BondingCurve as OnchainState>::REQUIRED_LEN,
            super::super::constants::BONDING_CURVE_ACCOUNT_SIZE,
        );
    }

    /// One byte of the cashback group but not both is truncation, not an
    /// older account.
    ///
    /// Both flags shipped in one upgrade, so an account carrying byte 81 and
    /// not 82 is corrupt. Reading the byte that happens to be there would
    /// invent a version that never existed; absence of the *whole* group is
    /// the only legitimate older layout.
    #[test]
    fn a_half_present_version_group_is_refused_not_half_read() {
        let curve = sample();
        let mut data = encode_81(&curve);
        data.push(1); // byte 81 present, byte 82 missing
        assert_eq!(data.len(), 82);
        let err = BondingCurve::from_account_data(&data).unwrap_err();
        assert!(
            format!("{err}").contains("cashback"),
            "expected the truncated-group error, got: {err}"
        );

        // The complete group parses, and the complete absence of it parses.
        assert!(BondingCurve::from_account_data(&encode_81(&curve)).is_ok());
        assert!(BondingCurve::from_account_data(&encode_83(&curve)).is_ok());
    }

    /// Wrong discriminator is refused here, not merely upstream.
    ///
    /// This inverts an earlier test which asserted the parse ignored the
    /// discriminator, on the reasoning that "the registry won't dispatch us".
    /// That reasoning was already false: `from_account_data` is public and
    /// `trading-execution` calls it straight off an RPC response, where no
    /// registry ever routed anything. A check the caller has to have performed
    /// elsewhere is a check that does not run.
    #[test]
    fn from_account_data_refuses_a_foreign_discriminator() {
        let mut data = encode_81(&sample());
        data[..8].copy_from_slice(&[0xFFu8; 8]);
        assert!(BondingCurve::from_account_data(&data).is_err());
    }

    #[test]
    fn spot_price_is_positive_on_fresh_curve() {
        let curve = sample();
        assert!(curve.spot_price() > 0.0);
    }

    #[test]
    fn is_active_tracks_complete_flag() {
        let mut curve = sample();
        assert!(curve.is_active());
        curve.complete = true;
        assert!(!curve.is_active());
    }
}
