//! Pump.fun create instruction types.
//!
//! This module provides types for parsing CREATE instructions.
//! Note: CREATE is typically not built by traders - it's used by token creators.

use solana_protocols_macros::InstructionData;
use serde::{Deserialize, Serialize};
use solana_program::pubkey::Pubkey;
use solana_protocols_macros::AccountMetas;



/// Account list for pump.fun create instruction.
///
/// `FromAccountKeys` is auto-generated by `#[derive(AccountMetas)]`.
#[derive(Debug, Clone, AccountMetas)]
#[idl(program = "pump", instruction = "create")]
#[accounts(unverified = "the legacy pre-2024 `create`; not seen once in a firehose capture, so there is no real instruction to pin the account list against")]
pub struct CreateAccounts {
    /// Token mint (created by this instruction).
    #[account(writable, signer)]
    pub mint: Pubkey,
    /// Mint authority.
    #[account]
    pub mint_authority: Pubkey,
    /// Bonding curve PDA.
    #[account(writable)]
    pub bonding_curve: Pubkey,
    /// Associated bonding curve token account.
    #[account(writable)]
    pub associated_bonding_curve: Pubkey,
    /// Global state.
    #[account]
    pub global: Pubkey,
    /// MPL token metadata program.
    #[account]
    pub mpl_token_metadata: Pubkey,
    /// Token metadata account.
    #[account(writable)]
    pub metadata: Pubkey,
    /// Creator wallet (signer).
    #[account(writable, signer)]
    pub user: Pubkey,
    /// System program.
    #[account]
    pub system_program: Pubkey,
    /// SPL Token program.
    #[account]
    pub token_program: Pubkey,
    /// Associated token program.
    #[account]
    pub associated_token_program: Pubkey,
    /// Rent sysvar.
    #[account]
    pub rent: Pubkey,
    /// Event authority PDA.
    #[account]
    pub event_authority: Pubkey,
    /// Pumpfun program.
    #[account]
    pub program: Pubkey,
}

// FromAccountKeys for CreateAccounts — auto-generated by #[derive(AccountMetas)] macro

/// Parameters for a create instruction.
///
/// Contains the token metadata (name, symbol, uri).
#[derive(Debug, Clone, Serialize, Deserialize, borsh::BorshDeserialize, borsh::BorshSerialize, InstructionData)]
#[instruction_data(discriminator = super::super::constants::CREATE_DISCRIMINATOR, unverified = "the legacy pre-2024 `create`; not seen once in a firehose capture, so there is no real instruction to pin it against", idl(program = "pump", instruction = "create"))]
pub struct CreateParams {
    /// Token name.
    pub name: String,
    /// Token symbol.
    pub symbol: String,
    /// Metadata URI (IPFS or HTTP).
    pub uri: String,
    /// The coin's creator, and the seed of its `creator_vault`.
    ///
    /// Declared by `pump.json` and simply absent from this struct: the
    /// hand-rolled decoder read three strings and stopped, so the fourth
    /// argument was discarded on every `create` we ever parsed. borsh refusing
    /// the leftover is what surfaced it.
    pub creator: Pubkey,
}

impl CreateParams {
    /// Create new create parameters.
    ///
    /// `creator` is required rather than defaulted: it seeds the coin's
    /// `creator_vault`, so a zero there would build a launch whose fees accrue
    /// to an address nobody holds.
    #[must_use]
    pub fn new(name: String, symbol: String, uri: String, creator: Pubkey) -> Self {
        CreateParams {
            name,
            symbol,
            uri,
            creator,
        }
    }
}



#[cfg(test)]
mod tests {
    use super::*;
    use super::super::super::constants::CREATE_DISCRIMINATOR;
    use crate::parsing::FromInstructionData;

    #[test]
    fn create_params_roundtrip() {
        let params = CreateParams::new(
            "Test Token".to_string(),
            "TEST".to_string(),
            "https://example.com/meta.json".to_string(),
            Pubkey::new_unique(),
        );

        let data = params.to_data();

        // Skip discriminator (8 bytes)
        let parsed = CreateParams::from_instruction_data(&data[8..]).unwrap();

        assert_eq!(parsed.name, "Test Token");
        assert_eq!(parsed.symbol, "TEST");
        assert_eq!(parsed.uri, "https://example.com/meta.json");
    }

    #[test]
    fn create_params_serialization() {
        let params = CreateParams::new(
            "Test".to_string(),
            "TST".to_string(),
            "https://x.com".to_string(),
            Pubkey::new_unique(),
        );

        let data = params.to_data();

        // Check discriminator
        assert_eq!(&data[0..8], &CREATE_DISCRIMINATOR);

        // Parse back the strings manually
        let mut offset = 8; // Skip discriminator

        // Name: length 4 + "Test" 4 = 8 bytes
        let name_len = u32::from_le_bytes(data[offset..offset + 4].try_into().unwrap()) as usize;
        assert_eq!(name_len, 4);
        offset += 4;
        assert_eq!(&data[offset..offset + name_len], b"Test");
    }
}
