//! Pump.fun create instruction types.
//!
//! This module provides types for parsing CREATE instructions.
//! Note: CREATE is typically not built by traders - it's used by token creators.

use serde::{Deserialize, Serialize};
use solana_program::pubkey::Pubkey;
use solana_protocols_macros::AccountMetas;

use crate::parsing::{FromInstructionData, InstructionParseError};

use super::super::constants::CREATE_DISCRIMINATOR;

/// Account list for pump.fun create instruction.
///
/// `FromAccountKeys` is auto-generated by `#[derive(AccountMetas)]`.
#[derive(Debug, Clone, AccountMetas)]
pub struct CreateAccounts {
    /// Token mint (created by this instruction).
    #[account(writable, signer)]
    pub mint: Pubkey,
    /// Mint authority.
    #[account]
    pub mint_authority: Pubkey,
    /// Bonding curve PDA.
    #[account(writable)]
    pub bonding_curve: Pubkey,
    /// Associated bonding curve token account.
    #[account(writable)]
    pub associated_bonding_curve: Pubkey,
    /// Global state.
    #[account]
    pub global: Pubkey,
    /// MPL token metadata program.
    #[account]
    pub mpl_token_metadata: Pubkey,
    /// Token metadata account.
    #[account(writable)]
    pub metadata: Pubkey,
    /// Creator wallet (signer).
    #[account(writable, signer)]
    pub user: Pubkey,
    /// System program.
    #[account]
    pub system_program: Pubkey,
    /// SPL Token program.
    #[account]
    pub token_program: Pubkey,
    /// Associated token program.
    #[account]
    pub associated_token_program: Pubkey,
    /// Rent sysvar.
    #[account]
    pub rent: Pubkey,
    /// Event authority PDA.
    #[account]
    pub event_authority: Pubkey,
    /// Pumpfun program.
    #[account]
    pub program: Pubkey,
}

// FromAccountKeys for CreateAccounts — auto-generated by #[derive(AccountMetas)] macro

/// Parameters for a create instruction.
///
/// Contains the token metadata (name, symbol, uri).
#[derive(Debug, Clone, Serialize, Deserialize, borsh::BorshDeserialize, borsh::BorshSerialize)]
pub struct CreateParams {
    /// Token name.
    pub name: String,
    /// Token symbol.
    pub symbol: String,
    /// Metadata URI (IPFS or HTTP).
    pub uri: String,
}

impl CreateParams {
    /// Create new create parameters.
    #[must_use]
    pub fn new(name: String, symbol: String, uri: String) -> Self {
        CreateParams { name, symbol, uri }
    }

    /// Serialize to instruction data.
    #[must_use]
    pub fn to_data(&self) -> Vec<u8> {
        let mut data = Vec::new();
        data.extend_from_slice(&CREATE_DISCRIMINATOR);

        // Borsh string encoding: 4-byte length + UTF-8 bytes
        let name_bytes = self.name.as_bytes();
        data.extend_from_slice(&(name_bytes.len() as u32).to_le_bytes());
        data.extend_from_slice(name_bytes);

        let symbol_bytes = self.symbol.as_bytes();
        data.extend_from_slice(&(symbol_bytes.len() as u32).to_le_bytes());
        data.extend_from_slice(symbol_bytes);

        let uri_bytes = self.uri.as_bytes();
        data.extend_from_slice(&(uri_bytes.len() as u32).to_le_bytes());
        data.extend_from_slice(uri_bytes);

        data
    }
}

impl FromInstructionData for CreateParams {
    fn from_instruction_data(data: &[u8]) -> Result<Self, InstructionParseError> {
        let mut offset = 0;

        let name = parse_borsh_string(data, &mut offset)?;
        let symbol = parse_borsh_string(data, &mut offset)?;
        let uri = parse_borsh_string(data, &mut offset)?;

        Ok(CreateParams { name, symbol, uri })
    }
}

/// Parse a single Borsh-encoded string.
fn parse_borsh_string(data: &[u8], offset: &mut usize) -> Result<String, InstructionParseError> {
    if *offset + 4 > data.len() {
        return Err(InstructionParseError::DeserializationFailed(format!(
            "not enough data for string length at offset {}",
            offset
        )));
    }

    let len = u32::from_le_bytes(data[*offset..*offset + 4].try_into().map_err(|_| {
        InstructionParseError::DeserializationFailed("invalid length bytes".to_string())
    })?) as usize;

    *offset += 4;

    if *offset + len > data.len() {
        return Err(InstructionParseError::DeserializationFailed(format!(
            "string length {} exceeds data at offset {}",
            len, offset
        )));
    }

    let s = std::str::from_utf8(&data[*offset..*offset + len])
        .map_err(|e| InstructionParseError::DeserializationFailed(format!("invalid UTF-8: {}", e)))?
        .to_string();

    *offset += len;

    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn create_params_roundtrip() {
        let params = CreateParams::new(
            "Test Token".to_string(),
            "TEST".to_string(),
            "https://example.com/meta.json".to_string(),
        );

        let data = params.to_data();

        // Skip discriminator (8 bytes)
        let parsed = CreateParams::from_instruction_data(&data[8..]).unwrap();

        assert_eq!(parsed.name, "Test Token");
        assert_eq!(parsed.symbol, "TEST");
        assert_eq!(parsed.uri, "https://example.com/meta.json");
    }

    #[test]
    fn create_params_serialization() {
        let params = CreateParams::new(
            "Test".to_string(),
            "TST".to_string(),
            "https://x.com".to_string(),
        );

        let data = params.to_data();

        // Check discriminator
        assert_eq!(&data[0..8], &CREATE_DISCRIMINATOR);

        // Parse back the strings manually
        let mut offset = 8; // Skip discriminator

        // Name: length 4 + "Test" 4 = 8 bytes
        let name_len = u32::from_le_bytes(data[offset..offset + 4].try_into().unwrap()) as usize;
        assert_eq!(name_len, 4);
        offset += 4;
        assert_eq!(&data[offset..offset + name_len], b"Test");
    }
}
