//! SPL Token Transfer instruction types.
//!
//! Account layout from SPL Token program.
//! Field order = on-chain account order.

use solana_program::pubkey::Pubkey;
use solana_protocols_macros::{AccountMetas, InstructionData};

use super::super::constants::TRANSFER_DISCRIMINATOR;

/// SPL Token Transfer instruction accounts.
///
/// `FromAccountKeys` is auto-generated by `#[derive(AccountMetas)]`.
#[derive(Debug, Clone, AccountMetas)]
#[accounts(unverified = "this protocol is not modelled to the pumpfun/pumpswap standard yet; a golden fixture here would claim a verification the rest of the vertical does not have")]
pub struct TransferAccounts {
    /// Source token account.
    #[account(writable)]
    pub source: Pubkey,
    /// Destination token account.
    #[account(writable)]
    pub destination: Pubkey,
    /// Transfer authority (owner or delegate).
    #[account(signer)]
    pub authority: Pubkey,
}

/// SPL Token Transfer instruction parameters.
///
/// `FromInstructionData` is auto-generated by `#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, InstructionData)]`.
#[derive(Debug, Clone, borsh::BorshDeserialize, borsh::BorshSerialize, InstructionData)]
#[instruction_data(discriminator = TRANSFER_DISCRIMINATOR, discriminator_size = 1, unverified = "this protocol is not modelled to the pumpfun/pumpswap standard yet; pinning params here would claim a verification the rest of the vertical does not have")]
pub struct TransferParams {
    /// Amount of tokens to transfer in raw units.
    pub amount: u64,
}

impl TransferParams {
    /// Create new transfer parameters.
    #[must_use]
    pub fn new(amount: u64) -> Self {
        Self { amount }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parsing::{FromAccountKeys, FromInstructionData};

    #[test]
    fn transfer_accounts_count() {
        assert_eq!(TransferAccounts::ACCOUNT_COUNT, 3);
    }

    #[test]
    fn transfer_params_roundtrip() {
        let params = TransferParams::new(1_000_000);
        let data = params.to_data();

        assert_eq!(data.len(), 9); // 1 disc + 8 amount
        assert_eq!(data[0], 3); // Transfer discriminator

        let parsed = TransferParams::from_instruction_data(&data[1..]).unwrap();
        assert_eq!(parsed.amount, 1_000_000);
    }

    #[test]
    fn transfer_accounts_from_keys() {
        let source = Pubkey::new_unique();
        let dest = Pubkey::new_unique();
        let authority = Pubkey::new_unique();
        let keys = vec![source, dest, authority];

        let accounts = TransferAccounts::from_account_keys(&keys).unwrap();
        assert_eq!(accounts.source, source);
        assert_eq!(accounts.destination, dest);
        assert_eq!(accounts.authority, authority);
    }
}
