//! SPL Token TransferChecked instruction types.
//!
//! TransferChecked is the preferred transfer instruction for Token-2022.
//! It includes the mint and decimals for verification.
//!
//! Account layout from SPL Token program.
//! Field order = on-chain account order.

use solana_program::pubkey::Pubkey;
use solana_protocols_macros::{AccountMetas, InstructionData};

use super::super::constants::TRANSFER_CHECKED_DISCRIMINATOR;

/// SPL Token TransferChecked instruction accounts.
///
/// `FromAccountKeys` is auto-generated by `#[derive(AccountMetas)]`.
#[derive(Debug, Clone, AccountMetas)]
pub struct TransferCheckedAccounts {
    /// Source token account.
    #[account(writable)]
    pub source: Pubkey,
    /// Token mint (for verification).
    #[account]
    pub mint: Pubkey,
    /// Destination token account.
    #[account(writable)]
    pub destination: Pubkey,
    /// Transfer authority (owner or delegate).
    #[account(signer)]
    pub authority: Pubkey,
}

/// SPL Token TransferChecked instruction parameters.
///
/// `FromInstructionData` is auto-generated by `#[derive(InstructionData)]`.
#[derive(Debug, Clone, InstructionData)]
#[instruction_data(discriminator = TRANSFER_CHECKED_DISCRIMINATOR, discriminator_size = 1)]
pub struct TransferCheckedParams {
    /// Amount of tokens to transfer in raw units.
    pub amount: u64,
    /// Expected number of base-10 digits to the right of the decimal place.
    pub decimals: u8,
}

impl TransferCheckedParams {
    /// Create new transfer checked parameters.
    #[must_use]
    pub fn new(amount: u64, decimals: u8) -> Self {
        Self { amount, decimals }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parsing::{FromAccountKeys, FromInstructionData};

    #[test]
    fn transfer_checked_accounts_count() {
        assert_eq!(TransferCheckedAccounts::ACCOUNT_COUNT, 4);
    }

    #[test]
    fn transfer_checked_params_roundtrip() {
        let params = TransferCheckedParams::new(500_000, 6);
        let data = params.to_data();

        assert_eq!(data.len(), 10); // 1 disc + 8 amount + 1 decimals
        assert_eq!(data[0], 12); // TransferChecked discriminator

        let parsed = TransferCheckedParams::from_instruction_data(&data[1..]).unwrap();
        assert_eq!(parsed.amount, 500_000);
        assert_eq!(parsed.decimals, 6);
    }

    #[test]
    fn transfer_checked_accounts_from_keys() {
        let source = Pubkey::new_unique();
        let mint = Pubkey::new_unique();
        let dest = Pubkey::new_unique();
        let authority = Pubkey::new_unique();
        let keys = vec![source, mint, dest, authority];

        let accounts = TransferCheckedAccounts::from_account_keys(&keys).unwrap();
        assert_eq!(accounts.source, source);
        assert_eq!(accounts.mint, mint);
        assert_eq!(accounts.destination, dest);
        assert_eq!(accounts.authority, authority);
    }
}
